apps/orion/urls.py
from django.urls import path

from apps.orion import views

app_name = 'orion'

urlpatterns = [
     path('', views.ChamadoHomeList.as_view(), name='lista_home'),
     path('chamados/', views.ChamadoList.as_view(), name='lista_chamados'),
     path('chamados/busca/', views.busca_chamados, name='busca_chamados'),
     path('chamados/fechados/', views.ChamadosFechadosList.as_view(), name='chamados_fechados'),
     path('chamado/fechar/<int:id>/', views.fechar_chamado, name='fechar_chamado'),
     path('chamado/novo/', views.novo_chamado, name='novo_chamado'),
     path('chamado/editar/<int:id>/', views.editar_chamado, name='editar_chamado'),
     path('chamado/deletar/<int:id>/', views.deletar_chamado, name='deletar_chamado'),


     path('carga_horaria/editar/<int:id>/', views.editar_carga_horaria, name = 'editar_carga_horaria'),
     path('nova_carga_horaria', views.nova_carga_horaria, name = 'nova_carga_horaria'),
     
     
     path('equipamentos/', views.EquipamentoList.as_view(), name='equipamentos'),
     path('equipamentos/<int:id>/', views.EquipamentoDetail.as_view(),name='detalhar_equipamento'),
     path('equipamentos_select2/<int:id>/', views.equipamentos_select2, name='equipamentos_select2'),
     path('equipamentos/novo', views.EquipamentoDetail.as_view(), name='cadastrar_equipamentos'),
     
     path('equipamentos/deletar/<int:id>/', views.EquipamentoDelete.as_view(), name='deletar_equipamento'),
     
     path('empresas/', views.empresas, name='empresas'),
     path('empresas/<int:id>/', views.detalhar_empresa, name='detalhar_empresa'),
     path('empresas/deletar/', views.deletar_empresa, name='deletar_empresa'),
     path('empresas/nova/', views.cadastrar_empresa, name='cadastrar_empresa'),
     
     path('assinatura_popup', views.assinatura_popup, name='assinatura_popup'),
     path('marcar_notificacao_como_lida', views.marcar_notificacao_como_lida, name = "marcar_notificacao_como_lida"),
     path('relatorio_ponto', views.relatorio_ponto, name = "relatorio_ponto"),
     path('download/', views.download_file, name='download_file'),
     path('teste', views.teste, name='teste'),
     path('list_teste', views.list_teste, name='list_teste'),

]

orion/urls.py
from django.urls import path

from orion import views

app_name = 'orion'

urlpatterns = [
     path('', views.lista_home, name='lista_home'),
     path('chamados/', views.lista_chamados, name='lista_chamados'),
     path('chamados/busca/', views.busca_chamados, name='busca_chamados'),
     path('chamados_fechados/', views.chamados_fechados, name='chamados_fechados'),
     path('fechar_chamado/<int:id>/', views.fechar_chamado, name='fechar_chamado'),
     path('chamados/<int:id>/', views.novo_chamado_view, name='novo_chamado_view'),
     path('novo_chamado/', views.novo_chamado, name='novo_chamado'),
     path('editar_chamado/<int:id>/', views.editar_chamado, name='editar_chamado'),
     path('deletar_chamado/<int:id>/', views.deletar_chamado, name='deletar_chamado'),
     path('equipamentos/', views.equipamentos, name='equipamentos'),
     path('equipamentos/<int:id>/', views.detalhar_equipamento,name='detalhar_equipamento'),
     path('equipamentos_select2/<int:id>/', views.equipamentos_select2, name='equipamentos_select2'),
          
     path('cadastrar_equipamentos/', views.cadastrar_equipamentos,
          name='cadastrar_equipamentos'),
     path('deletar_equipamento/<int:id>/',
          views.deletar_equipamento, name='deletar_equipamento'),
     path('clientes/', views.clientes, name='clientes'),
     path('clientes/<int:id>/', views.detalhar_cliente, name='detalhar_cliente'),
     path('deletar_cliente/',
          views.deletar_cliente, name='deletar_cliente'),
     path('cadastrar_clientes/', views.cadastrar_clientes, name='cadastrar_clientes'),
     path('assinatura_popup', views.assinatura_popup, name='assinatura_popup'),
     path('marcar_notificacao_como_lida', views.marcar_notificacao_como_lida, name = "marcar_notificacao_como_lida"),
     path('relatorio_ponto', views.relatorio_ponto, name = "relatorio_ponto"),
     path('download/', views.download_file, name='download_file'),
     path('teste', views.teste, name='teste'),
     path('list_teste', views.list_teste, name='list_teste'),

]

setup/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.orion.urls')),
    path('', include('apps.usuarios.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/orion/models.py
from datetime import datetime, time

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from jsignature.fields import JSignatureField

from apps.usuarios.models import Usuario

#from smart_selects.db_fields import ChainedForeignKey


# from validate_docbr import CPF

# Create your models here.


class Endereco(models.Model):
    rua = models.CharField(max_length=100)
    numero = models.IntegerField()
    bairro = models.CharField(max_length=50)
    cep = models.CharField(max_length=8)
    uf = models.CharField(max_length=2)
    cidade = models.CharField(max_length=100)
    complemento = models.CharField(max_length=100, blank=True, null=True)
    def __str__(self):
        return f'{self.rua}, {self.numero} - {self.bairro}, {self.cidade}-{self.uf}, {self.cep}'


class Empresa (models.Model):
    nome       = models.CharField(max_length=100)
    cnpj       = models.CharField(max_length=14)
    telefone   = models.CharField(max_length=14, null=True, blank=True)
    email      = models.CharField(max_length=35,null=True, blank=True)
    observacao = models.CharField(max_length=280, null=True, blank=True)#
    endereco   = models.OneToOneField(Endereco, on_delete=models.SET_NULL, 
                                      null=True, blank=True, related_name='empresa')

    
    def __str__(self):
        return f'{self.nome}'


class Equipamento(models.Model):
    empresa          = models.ForeignKey(Empresa, on_delete=models.SET_NULL, related_name='equipamento', null=True, blank=True)
    numero_serie     = models.CharField(max_length=100)
    equipamento      = models.CharField(max_length=100)
    tipo_equipamento = models.CharField(max_length=35)
    descricao        = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return f'{self.equipamento}'


class TIPO_STATUS(models.TextChoices):
    PARADO = 'P', _('Parado')
    RESTRITO = 'R', _('Restrito')
    NORMAL = 'N', _('Normal')
    OUTROS = 'O', _('Outros')


class Chamado(models.Model):
    TIPO_DE_CHAMADO = (('C', 'Contrato'), ('A', 'Avulso'))
    
    STATUS_CHAMADO = (('A', 'Aberto'), ('F', 'Fechado'))
    
    status = models.CharField(
        max_length=1, choices=TIPO_STATUS.choices, blank=False, null=False, default='P')
    
    tipo_chamado = models.CharField(
        max_length=1, choices=TIPO_DE_CHAMADO, blank=False, null=False, default='C')

    status_chamado = models.CharField(
        max_length=1, choices=STATUS_CHAMADO, default='A')

    numero_chamado = models.CharField(max_length=14)  # YYYY DD MM HHHH SS
    descricao_chamado = models.CharField(max_length=150, blank=False)
    descricao_servico = models.TextField(null=True, blank=True)
    observacoes_do_cliente = models.TextField(blank=True, null = True)
    criado_em = models.DateTimeField(auto_now_add=True)
    atualizado_em = models.DateTimeField(auto_now=True)

    empresa = models.ForeignKey(
        Empresa, on_delete=models.SET_NULL, related_name='ordem_servico', null=True, blank=True)

    equipamento = models.ForeignKey(Equipamento, on_delete=models.SET_NULL, null=True, blank=True)

    contato = models.CharField(max_length=100, null=True, blank=True)
    
    aberto_por = models.ForeignKey(
        Usuario, on_delete=models.SET_NULL, null=True, related_name='ordem_servico')

    assinatura = JSignatureField(null=True, blank=True)
    
    def __str__(self):
        return f'Status = {self.status}, Tipo de chamado - {self.tipo_chamado}, - Criado em {self.criado_em}'

    def get_absolute_url(self):
        return reverse("orion:editar_chamado", args=(self.pk,))
    

class CargaHoraria(models.Model):
    data = models.DateField()
    hora_inicio = models.TimeField()
    hora_termino = models.TimeField()
    horas_de_trabalho = models.TimeField()
    status = models.CharField(
        max_length=1, choices=TIPO_STATUS.choices, blank=False, null=False, default='N')
    tecnico = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='carga_horaria')

    ordem_servico = models.ForeignKey(
        Chamado, on_delete=models.SET_NULL, null=True, related_name='carga_horaria')

    def __str__(self):
        return f'dia = {self.data} -Entrada =  {self.hora_inicio} -Saida =  {self.hora_termino}'

    def save(self, *args, **kwargs):
        # Convertendo cada objeto datetime.time em um objeto datetime
        hora_inicio = datetime.combine(self.data, self.hora_inicio)
        hora_termino = datetime.combine(self.data, self.hora_termino)
        
        # Calcule a diferença entre os dois horarios
        diferenca = hora_termino - hora_inicio
        
        diferenca_horas, diferenca_segundos = divmod(diferenca.seconds, 3600)
        diferenca_minutos, _ = divmod(diferenca_segundos, 60)
        #horas trabalhadas
        self.horas_de_trabalho= time(hour=diferenca_horas, minute=diferenca_minutos, second=0)
        super(CargaHoraria, self).save(*args, **kwargs)


class TIPO_DESPESA(models.TextChoices):
    ALIMENTACAO = 'AL', _('Alimentação')
    BAGAGEM = 'BA', _('Bagagem')
    ALUGUEL_CARROS = 'AC', _('Aluguel de carros')
    COMBUSTIVEL = 'CO', _('Combustível')
    CORREIO_FRETE = 'CF', _('Correio/Frete')
    ESTACIONAMENTO = 'ES', _('Estacionamento')
    FRIGOBAR = 'FR', _('Friogobar')
    HOSPEDAGEM = 'HO', _('Hospedagem')
    LAVANDERIA = 'LA', _('Lavanderia')
    COMPRA_DE_MATERIAL = 'CM', _('Compra de material')
    PAGAMENTOS = 'PG', _('Pagamentos')
    PASSAGEM_AERIA = 'PA', _('Passagem Aéria')
    TRANSPORTE = 'TR', _('Transporte')
    OUTROS = 'OT', _('Outros')

class Despesa(models.Model):
    tipo = models.CharField(
        max_length=2, choices=TIPO_DESPESA.choices, blank=False, null=False, default='AL')
    data = models.DateField()
    valor = models.DecimalField(max_digits=10, decimal_places=2)
    tecnico = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='despesa')
    ordem_servico = models.ForeignKey(Chamado, on_delete=models.SET_NULL, null=True, related_name='despesa')

    def __str__(self):
        return f'tipo = {self.tipo} -data =  {self.data} - valor =  {self.valor}'


class SignatureModel(models.Model):
    signature = JSignatureField()

apps/orion/views/chamado.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import ListView

from apps.orion import utils
from apps.orion.models import Chamado
from apps.usuarios.models import Usuario


@method_decorator(login_required(login_url='usuarios:login' ,redirect_field_name='next'), name='dispatch' )
class ChamadoList(ListView):
    model = Chamado
    context_object_name = "chamados"
    template_name = 'orion/pages/chamado_list.html'
    
    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        
        qs = qs.select_related('empresa', 'equipamento').filter(status_chamado='A').order_by('-id')
        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        chamado_page = utils.paginacao(self.request, ctx.get('chamados'))
        ctx.update({'chamados': chamado_page })
        ctx['titulo'] = f'Chamados abertos'
        return ctx
    
@method_decorator(login_required(login_url='usuarios:login' ,redirect_field_name='next'), name='dispatch' )
class ChamadoHomeList(ChamadoList):

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        usuario = Usuario.objects.get(user_id=self.request.user.id)
        qs = qs.filter(aberto_por=usuario)
        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        ctx['home'] = f'Olá, {self.request.user.username.title()}'
        return ctx
    
@method_decorator(login_required(login_url='usuarios:login' ,redirect_field_name='next'), name='dispatch' )
class ChamadosFechadosList(ChamadoList):

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        
        qs = Chamado.objects.all().select_related('empresa', 'equipamento').filter(
        status_chamado='F').order_by('-id')
        return qs
    
    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        ctx['titulo'] = f'Chamados fechados'
        return ctx

apps/orion/views/equipamento.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.http.response import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import ListView

from apps.orion import utils
from apps.orion.forms import EquipamentosForm
from apps.orion.models import Equipamento


@login_required
def equipamentos_select2(request, id):
    dados = Equipamento.objects.filter(empresa=id)
    dados_json = [{'id': d.id, 'nome': d.equipamento} for d in dados]
    return JsonResponse(dados_json, safe=False)

@method_decorator(login_required(login_url='usuarios:login' ,redirect_field_name='next'), name='dispatch' )
class EquipamentoList(ListView):
    model = Equipamento
    context_object_name = "equipamentos"
    template_name = 'orion/pages/equipamentos.html'
    ordering = '-id'
    
    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.select_related('empresa')
        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        equipamento_page = utils.paginacao(self.request, ctx.get('equipamentos'))
        ctx.update({'equipamentos': equipamento_page })
        return ctx

@method_decorator(login_required(login_url='usuarios:login' ,redirect_field_name='next'), name='dispatch' )
class EquipamentoDetail(View):
    
    def get_equipamento(self, id):
        equipamento = None
        if id:  
            equipamento = get_object_or_404(Equipamento, pk=id )

        return equipamento
         

    def render_equipamento(self, form, id ):
        return render(self.request, 'orion/pages/detalhes_equipamentos.html', { 'form': form, 'id': id})

    def get(self, request, id=None):
        equipamento = self.get_equipamento(id)
        equipamentoForm = EquipamentosForm(instance=equipamento)
        return self.render_equipamento(equipamentoForm, id)

    def post(self, request, id=None):
        equipamento = self.get_equipamento(id)
        equipamentoForm = EquipamentosForm(self.request.POST, instance=equipamento)
        
        if equipamentoForm.is_valid():
            messages.success(self.request, "Equipamento Salvo com Sucesso")
            equipamentoForm.save()
            return redirect('orion:equipamentos')
        else:
            return self.render_equipamento(equipamentoForm, id)
            
@method_decorator(login_required(login_url='usuarios:login' ,redirect_field_name='next'), name='dispatch' )
class EquipamentoDelete(EquipamentoDetail):
    def post(self, request, id=None):
        #post(self, *args, **kwargs): self.request.POST.get('id')
        equipamento = self.get_equipamento(id)
        equipamento.delete()
        messages.success(self.request, "Equipamento deletado com sucesso")
        return redirect('orion:equipamentos')

apps/orion/templates/orion/pages/detalhes_cliente.html
{% extends "globals/base.html"%}
{% load widget_tweaks %}

{% block content %}

<br>

<div class="panel-heading">
    <h3 class="panel-title">{{ titulo }}</h3>
</div>


<div class="container col-sm-10">
    <br>

    <form action="" id="form-cliente" method="post">
        {% csrf_token %}

        {% include 'globals/partials/_form.html' with form=form %}
        
        <div id="targetEndereco">
        {% if formEndereco.instance  %}
            {% include 'globals/partials/_form.html' with form=formEndereco %}
 
        {% endif %}    
        </div>
    
        </form>    
        
        {% if formEndereco.instance is False  %}
        <!-- Modal -->
            <div id="div_adicionar_endereco" class="form-group mt-3 mb-3 row d-flex">
                <div class="label-class col-sm-2 text-start text-sm-end">
                <label class="col-form-label" for="adicionar_endereco">
                    Endereço:  </label>
                </div>
                    <div class="col-sm-3 d-flex">
                        <input id = "adicionar_endereco" type="text" class="form-control" placeholder ="Cadastrar Endereço" disabled>
                        <button class="btn btn-success" type="button" id="btn_adicionar_endereco" 
                        data-bs-toggle="modal" data-bs-target="#enderecoModal"><i class="fa-solid fa-plus"></i></button>
                        
                        
                    </div>
            </div>
            {% include 'orion/partials/_endereco_modal.html' %}
        {% endif %}
    
    <div class="d-flex justify-content-center m-2">
        <button type="submit" class="btn btn-primary m-2" form="form-cliente" name="btn-salvar-cliente"> Salvar </button>
        
        {% if id %}
            <form action="{% url 'orion:deletar_cliente'%}" method="post">{% csrf_token %}
                <input type="hidden" name='id' value="{{ id }}" > </input>
                <button type="submit" class="btn btn-danger m-2"> Apagar </button>
            </form>
        {% endif %}
            
    </div>


    <!-- Adicionando JQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
    crossorigin="anonymous"></script>
    
    <script type="text/javascript">
        
        
        const salvarEnderecoBtn = document.getElementById("btn_salvar_endereco")
        
        if(salvarEnderecoBtn){

            salvarEnderecoBtn.addEventListener('click', salvar_endereco)
            
            function salvar_endereco(event){
                if(event){
                    event.preventDefault()   
                }
                const formCopyTarget = document.getElementById("targetEndereco")
                const copyFormEl = document.getElementById("endereco-modal").cloneNode(true);
                copyFormEl.setAttribute("id","endereco-form")
                formCopyTarget.append(copyFormEl)
                enderecoModal = document.getElementById("endereco-modal")
                enderecoModal.remove()
                
                //oculta o botão de add endereço
                const div_adicionar_endereco = document.getElementById("div_adicionar_endereco")
                div_adicionar_endereco.classList.remove('d-flex')
                div_adicionar_endereco.classList.add('hidden');
                
            } 
            
        }


        const buscaCepBtn = document.getElementById("buscaCep")
        
        buscaCepBtn.addEventListener('click', busca_cep)
        
        function busca_cep(event){
            if(event){
                event.preventDefault()   
            }
            buscaCepBtn.textContent = 'Processando...';
            var numCep = $("#id_cep").val();

            var url = "https://viacep.com.br/ws/"+ numCep +"/json/?callback=?";
            $.ajax({
                url:url,
                type:"get",
                dataType:"json",
                success:function(dados){
                    console.log(dados)
                    if(!dados.erro){

                        $("#id_rua").val(dados.logradouro);
                        $("#id_bairro").val(dados.bairro);
                        $("#id_uf").val(dados.uf);
                        $("#id_cidade").val(dados.localidade);
                    }else{ 
                        alert("Erro ao buscar o Cep"); 
                    }
                    buscaCepBtn.textContent = 'Buscar '

                },
                error: function(){
                    alert("Erro ao buscar o Cep");
                    buscaCepBtn.textContent = 'Buscar '
                }
            })
            
        } 
        // mascara de telefone 
        var SPMaskBehavior = function (val) {
            return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
          },
        spOptions = {
        onKeyPress: function(val, e, field, options) {
            field.mask(SPMaskBehavior.apply({}, arguments), options);
            }
        };

        $(document).ready(function(){
            $('.cep').mask('00000-000');
            $('.cnpj').mask('00.000.000/0000-00');
            $('.telefone').mask(SPMaskBehavior, spOptions);

        });

    </script>
</div>
{% endblock %}

apps/orion/templates/orion/pages/detalhes_empresa.html
{% extends "globals/base.html"%}
{% load widget_tweaks %}

{% block content %}

<br>

<div class="panel-heading">
    <h3 class="panel-title">{{ titulo }}</h3>
</div>


<div class="container col-sm-10">
    <br>

    <form action="" id="form-empresa" method="post">
        {% csrf_token %}

        {% include 'globals/partials/_form.html' with form=form %}
        
        <div id="targetEndereco">
        {% if formEndereco.instance  %}
            {% include 'globals/partials/_form.html' with form=formEndereco %}
 
        {% endif %}    
        </div>
    
        </form>    
        
        {% if formEndereco.instance is False  %}
        <!-- Modal -->
            <div id="div_adicionar_endereco" class="form-group mt-3 mb-3 row d-flex">
                <div class="label-class col-sm-2 text-start text-sm-end">
                <label class="col-form-label" for="adicionar_endereco">
                    Endereço:  </label>
                </div>
                    <div class="col-sm-3 d-flex">
                        <input id = "adicionar_endereco" type="text" class="form-control" placeholder ="Cadastrar Endereço" disabled>
                        <button class="btn btn-success" type="button" id="btn_adicionar_endereco" 
                        data-bs-toggle="modal" data-bs-target="#enderecoModal"><i class="fa-solid fa-plus"></i></button>
                        
                        
                    </div>
            </div>
            {% include 'orion/partials/_endereco_modal.html' %}
        {% endif %}
    
    <div class="d-flex justify-content-center m-2">
        <button type="submit" class="btn btn-primary m-2" form="form-empresa" name="btn-salvar-empresa"> Salvar </button>
        
        {% if id %}
            <form action="{% url 'orion:deletar_empresa'%}" method="post">{% csrf_token %}
                <input type="hidden" name='id' value="{{ id }}" > </input>
                <button type="submit" class="btn btn-danger m-2"> Apagar </button>
            </form>
        {% endif %}
            
    </div>


    <!-- Adicionando JQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
    crossorigin="anonymous"></script>
    
    <script type="text/javascript">
        
        
        const salvarEnderecoBtn = document.getElementById("btn_salvar_endereco")
        
        if(salvarEnderecoBtn){

            salvarEnderecoBtn.addEventListener('click', salvar_endereco)
            
            function salvar_endereco(event){
                if(event){
                    event.preventDefault()   
                }
                const formCopyTarget = document.getElementById("targetEndereco")
                const copyFormEl = document.getElementById("endereco-modal").cloneNode(true);
                copyFormEl.setAttribute("id","endereco-form")
                formCopyTarget.append(copyFormEl)
                enderecoModal = document.getElementById("endereco-modal")
                enderecoModal.remove()
                
                //oculta o botão de add endereço
                const div_adicionar_endereco = document.getElementById("div_adicionar_endereco")
                div_adicionar_endereco.classList.remove('d-flex')
                div_adicionar_endereco.classList.add('hidden');
                
            } 
            
        }


        const buscaCepBtn = document.getElementById("buscaCep")
        
        buscaCepBtn.addEventListener('click', busca_cep)
        
        function busca_cep(event){
            if(event){
                event.preventDefault()   
            }
            buscaCepBtn.textContent = 'Processando...';
            var numCep = $("#id_cep").val();

            var url = "https://viacep.com.br/ws/"+ numCep +"/json/?callback=?";
            $.ajax({
                url:url,
                type:"get",
                dataType:"json",
                success:function(dados){
                    console.log(dados)
                    if(!dados.erro){

                        $("#id_rua").val(dados.logradouro);
                        $("#id_bairro").val(dados.bairro);
                        $("#id_uf").val(dados.uf);
                        $("#id_cidade").val(dados.localidade);
                    }else{ 
                        alert("Erro ao buscar o Cep"); 
                    }
                    buscaCepBtn.textContent = 'Buscar '

                },
                error: function(){
                    alert("Erro ao buscar o Cep");
                    buscaCepBtn.textContent = 'Buscar '
                }
            })
            
        } 
        // mascara de telefone 
        var SPMaskBehavior = function (val) {
            return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009';
          },
        spOptions = {
        onKeyPress: function(val, e, field, options) {
            field.mask(SPMaskBehavior.apply({}, arguments), options);
            }
        };

        $(document).ready(function(){
            $('.cep').mask('00000-000');
            $('.cnpj').mask('00.000.000/0000-00');
            $('.telefone').mask(SPMaskBehavior, spOptions);

        });

    </script>
</div>
{% endblock %}

apps/orion/templates/orion/pages/equipamentos.html
{% extends "globals/base.html"%}
{% load widget_tweaks %}

{% block content %}

{% include 'globals/partials/_alertas.html' %}

<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-info">
            <br>
            <div class="panel-heading">
                <h3 class="panel-title">Equipamentos</h3>
            </div>

            <div class=" d-flex justify-content-end m-2">
                <a href="{% url 'orion:cadastrar_equipamentos' %}">  
                        <button type="submit" class="btn btn-primary"> Novo Equipamento</button>
                </a>
                
        
            </div>

            <div class="table-responsive table-sortable">

                <table class="table table-bordered table-striped">
                    <colgroup>
                        <col class="col-xs-2">
                        <col class="col-xs-2">
                        <col class="col-xs-2">
                        <col class="col-xs-1">
                        <col class="col-xs-1">
                        <col class="col-xs-2">
                        <col class="col-xs-1">
                    </colgroup>
                    <thead>
                        <tr>
                            <th>Equipamento</th>
                            <th>Tipo de Equipamento</th>
                            <th>Descrição</th>
                            <th>Número de Série</th>
                            <th>Empresa</th>
                            <th>Ações</th>
                        </tr>
                    </thead>
                    <tbody>

                        {% for equipamento in equipamentos %}
                        
                            <tr>
                                <td>{{ equipamento.equipamento}} </td>
                                <td>{{ equipamento.tipo_equipamento }}</td>
                                <td>{{ equipamento.descricao }} </td>
                                <td>{{ equipamento.numero_serie}} </td>
                                <td>{{ equipamento.empresa}} </td>
                                <td align="center"><a href="{% url 'orion:detalhar_equipamento' equipamento.id %}" title="Editar"><i
                                    class="fa-solid fa-pen-to-square"></i></a></td>
                            </tr>
                            
                        {% empty %}    
                            
                            <tr>
                                <td colspan="8">Sem registros</td>
                            </tr>
                        {% endfor %}
                            
                    </tbody>
                </table>

                {% include 'orion/partials/_paginacao.html' with form=equipamentos %}

            </div>
        </div>
    </div>
</div>

{% endblock %}