apps/usuarios/urls.py
from django.urls import path

from . import views

app_name = 'usuarios'

urlpatterns = [
    path('usuarios/', views.lista_usuarios, name='lista_usuarios'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('cadastro_usuario/', views.cadastro_usuario, name='cadastro_usuario'),
    path('deletar_usuario/<int:id>', views.deletar_usuario, name='deletar_usuario'),
    path('dados-usuario/', views.dados_usuario, name='dados_usuario'),
    path('editar-usuario/<int:id>', views.editar_usuario, name='editar_usuario'),
    path('usuario_teste/', views.usuario_teste, name='usuario_teste'),
]

orion/urls.py
from django.urls import path

from orion import views

app_name = 'orion'

urlpatterns = [
     path('', views.lista_home, name='lista_home'),
     path('chamados/', views.lista_chamados, name='lista_chamados'),
     path('chamados/busca/', views.busca_chamados, name='busca_chamados'),
     path('chamados_fechados/', views.chamados_fechados, name='chamados_fechados'),
     path('fechar_chamado/<int:id>/', views.fechar_chamado, name='fechar_chamado'),
     path('chamados/<int:id>/', views.novo_chamado_view, name='novo_chamado_view'),
     path('novo_chamado/', views.novo_chamado, name='novo_chamado'),
     path('editar_chamado/<int:id>/', views.editar_chamado, name='editar_chamado'),
     path('deletar_chamado/<int:id>/', views.deletar_chamado, name='deletar_chamado'),
     path('equipamentos/', views.equipamentos, name='equipamentos'),
     path('equipamentos/<int:id>/', views.detalhar_equipamento,name='detalhar_equipamento'),
     path('equipamentos_select2/<int:id>/', views.equipamentos_select2, name='equipamentos_select2'),
          
     path('cadastrar_equipamentos/', views.cadastrar_equipamentos,
          name='cadastrar_equipamentos'),
     path('deletar_equipamento/<int:id>/',
          views.deletar_equipamento, name='deletar_equipamento'),
     path('clientes/', views.clientes, name='clientes'),
     path('clientes/<int:id>/', views.detalhar_cliente, name='detalhar_cliente'),
     path('deletar_cliente/',
          views.deletar_cliente, name='deletar_cliente'),
     path('cadastrar_clientes/', views.cadastrar_clientes, name='cadastrar_clientes'),
     path('assinatura_popup', views.assinatura_popup, name='assinatura_popup'),
     path('marcar_notificacao_como_lida', views.marcar_notificacao_como_lida, name = "marcar_notificacao_como_lida"),
     path('relatorio_ponto', views.relatorio_ponto, name = "relatorio_ponto"),
     path('download/', views.download_file, name='download_file'),
     path('teste', views.teste, name='teste'),
     path('list_teste', views.list_teste, name='list_teste'),

]

setup/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.orion.urls')),
    path('', include('apps.usuarios.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/usuarios/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import gettext_lazy as _

# Create your models here.


class TIPO_USUARIO(models.TextChoices):
    ADMIN = 'A', _('Admin')
    TECNICO = 'T', _('Tecnico')


class Usuario(models.Model):
    user = models.ForeignKey(
        User, related_name='usuariouser', on_delete=models.CASCADE, null=True)
    tipo = models.CharField(max_length=1, choices=TIPO_USUARIO.choices, default='T')

    def __str__(self):
        return f'{self.user.username}'

apps/usuarios/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from .models import TIPO_USUARIO, Usuario


#Formulario de autenticação de usuários
class LoginForm(forms.Form):
    login = forms.CharField(
        label=False,
        max_length=100,
        required=True,
        widget= forms.TextInput(attrs={'placeholder':'Login', 'class':'form-control' }))
    
    senha = forms.CharField(
        label=False,
        max_length=100,
        required=True,
        widget = forms.PasswordInput(attrs={'placeholder':'Senha', 'class':'form-control'})
    )

class UserUpdateForm(UserChangeForm):
    password = forms.CharField( label='Senha', help_text= '* Ao deixar este campo vazio, a senha atual será mantida', required=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
    )
    
    password2 = forms.CharField( label='Confirmar Senha', required=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
    )
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs.update({'class': 'form-control'})
        self.fields['last_name'].widget.attrs.update({'class': 'form-control'})
        self.fields['username'].widget.attrs.update({'class': 'form-control'})
        self.fields['email'].widget.attrs.update({'class': 'form-control'})


    class Meta:
        model = User
        fields = ['username','first_name', 'last_name', 'email']
        readonly_fields = ('first_name', )
        labels = {
            'username': 'Login',  # Alterar o label do campo 
            'first_name': 'Nome',
            'last_name': 'Sobrenome',
            'email': 'E-mail',
        }
    
    def clean_password2(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        password2 = cleaned_data.get('password2')
        print("password2 = ",password2)
        print("cleaned_data = ",self.cleaned_data)
        
        if not password and not password2:
            # Mantém a senha atual se o campo de senha estiver vazio
            #print(self.instance.password)
            return None
        
        if password != password2:
            raise forms.ValidationError("As senhas não podem ser diferentes")

        return password
    
    def save(self, commit=True):
        user = super().save(commit=False)
        password = self.cleaned_data.get('password')
        if password:
            user.set_password(password)
            
        if commit:
            user.save()
        return user


class UsuarioForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        #self.fields['tipo'].widget.attrs['readonly'] = True
        #self.fields['tipo'].widget.attrs['disabled'] = True
        self.fields['tipo'].widget.attrs.update({'class': 'form-control'})

    class Meta:
        model = Usuario
        fields = ['tipo']



class CadastroUsuarioForm(forms.Form):
    nome = forms.CharField( label= "Nome",
        max_length=100,
        required=True,
        widget= forms.TextInput(attrs={'placeholder':'Digite o nome', 'class':'form-control' })
    )

    sobrenome = forms.CharField( label= "Sobrenome",
        max_length=100,
        required=True,
        widget= forms.TextInput(attrs={'placeholder':'Digite o sobrenome', 'class':'form-control' })
    )
    
    login = forms.CharField( label= "Login",
        max_length=100,
        required=True,
        widget= forms.TextInput(attrs={'placeholder':'Digite o login', 'class':'form-control' })
        )
    email = forms.CharField( label= "Email",
        max_length=100,
        required=True,
        widget= forms.TextInput(attrs={'placeholder':'Digite o email', 'class':'form-control' })
        )

    senha = forms.CharField( label="Senha",
        max_length=100,
        required=True,
        widget = forms.PasswordInput(attrs={'placeholder':'Digite a senha', 'class':'form-control'}))

    
    confirmacao_senha = forms.CharField( label="Senha",
        max_length=100,
        required=True,
        widget = forms.PasswordInput(attrs={'placeholder':'Confirme a senha', 'class':'form-control'}))

    tipo_usuario = forms.ChoiceField(choices = TIPO_USUARIO.choices, label="Tipo de Usuário", initial='T', widget=forms.Select(attrs={'class':'form-select'}), required=True)
                                    

   

    def clean_login(self):
        login = self.cleaned_data.get("login")
        if login:
            login = login.strip()
            if " " in login:
                raise forms.ValidationError("Login não pode conter espaços em branco")
            else:
                return login

    def clean(self):
        cleaned_data = super().clean()
        senha = cleaned_data.get('senha')
        senha2 = cleaned_data.get('confirmacao_senha')
        if senha != senha2:
            raise forms.ValidationError({'confirmacao_senha':"As senhas não podem ser diferentes"})
        else:
            return senha2
        
            

apps/usuarios/views.py
from django.contrib import auth, messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.forms import inlineformset_factory
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from apps.usuarios.forms import (CadastroUsuarioForm, LoginForm,
                                 UserUpdateForm, UsuarioForm)

from .models import Usuario


#utils
def isUserAdmin(user):
    usuario = get_object_or_404(Usuario, user_id=user.id)
    if usuario.tipo == 'A':
        return True
    return False

@login_required
def lista_usuarios(request):
    usuarios = Usuario.objects.select_related('user').all()
    contexto = {
        'forms': usuarios,
        'titulo': 'Lista de Usuários'
    }
    return render(request, 'usuarios/pages/lista_usuarios.html', contexto)

@login_required
def logout(request):
    auth.logout(request)
    messages.success(request, "Logout realizado com sucesso")
    print("Logout realizado com sucesso")
    return redirect(reverse('usuarios:login'))


def login(request):
    if request.user.is_authenticated:
        return redirect(reverse('orion:lista_home'))
    
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            login = form['login'].value().lower().strip()
            senha = form['senha'].value()
            usuario = auth.authenticate(
                request,
                username=login,
                password=senha
            )
            if usuario is not None:
                auth.login(request, usuario)
                next = request.GET.get("next", None)
                if next is not None:
                    return redirect(next)
                return redirect('orion:lista_home')

            
        messages.error(request, "Login ou Senha incorretos")
        return render(request, 'usuarios/pages/login.html', {'form': form})
    else:
        formLogin = LoginForm()
        contexto = {
            'form': formLogin
        }
        return render(request, 'usuarios/pages/login.html', contexto)

@login_required
def cadastro_usuario(request):
    if not request.user.is_authenticated:
        return redirect('login')
    usuario = get_object_or_404(Usuario, user_id=request.user.id)
    
    if usuario.tipo != 'A':
        messages.error(request, f"Usuário {usuario.user.username} não é Administrador")
        return redirect('orion:lista_home')


    if request.method == 'POST':
        form = CadastroUsuarioForm(request.POST)
        if form.is_valid():

            login     = form['login'].value()
            nome      = form['nome'].value()
            sobrenome = form['sobrenome'].value()
            email     = form['email'].value()
            senha     = form['senha'].value()

            tipo_usuario = form['tipo_usuario'].value()
           
            if User.objects.filter(username=login).exists():
                messages.error(request, f"O nome {login} já foi cadastrado.")
                return render(request, 'usuarios/pages/cadastro_usuario.html',  {'form': form})

            user = User.objects.create_user(
                username=login,
                first_name = nome,
                last_name= sobrenome,
                password=senha,
                email=email
            )
            user.save()

            usuario = Usuario.objects.create(user=user, tipo=tipo_usuario)
            usuario.save()
            messages.success(request, f"Usuário {login} salvo com sucesso.")

            return redirect('usuarios:lista_usuarios')

        return render(request, 'usuarios/pages/cadastro_usuario.html',  {'form': form})

    else:
        cadastroUsuarioForm = CadastroUsuarioForm()
        contexto = {
            'form': cadastroUsuarioForm
        }
        return render(request, 'usuarios/pages/cadastro_usuario.html', contexto)

@login_required
def deletar_usuario(request, id):
    if not request.user.is_authenticated:
        return redirect('usuarios:login')
    usuario_logado = get_object_or_404(Usuario, user_id=request.user.id)
    
    if usuario_logado.tipo != 'A':
        messages.error(request, f"Usuário {usuario_logado.user.username} não é Administrador")
        return redirect('orion:lista_home')
    try:
        user = get_object_or_404(User, pk=id)
        usuario = get_object_or_404(Usuario, user_id=id)
    except usuario.DoesNotExist:
        raise Http404("No MyModel matches the given query.")
    
    nome = usuario.user.username
    usuario.delete()
    user.delete()
    messages.success(request, f"Usuário {nome} excluido com sucesso")
    return redirect('usuarios:lista_usuarios')

@login_required(login_url="usuarios:login", redirect_field_name="next")
def dados_usuario(request):
    usuario = get_object_or_404(Usuario, user_id=request.user.id)
    
    if request.method == 'POST':
        form = UserUpdateForm(request.POST, instance =request.user)
        usuarioForm = UsuarioForm(request.POST)
        if form.is_valid():
            form.save()
            print("é valido")
            # Atualiza a sessão do usuário para evitar que ele seja desconectado após alterar a senha
            update_session_auth_hash(request, request.user)
            messages.success(request, "Editado com sucesso")
            return redirect('usuarios:lista_usuarios')
        
        print("não é valido")
        return render(request, 'usuarios/pages/dados_usuario.html', 
                {  'title':' Meus Dados',
                    'form': form,
                    'usuarioForm': usuarioForm  })
    else:
        userForm = UserUpdateForm(instance = request.user)
        usuarioForm = UsuarioForm(instance = usuario)
        
        if not isUserAdmin(request.user):
            usuarioForm.fields['tipo'].widget.attrs['readonly'] = True
            usuarioForm.fields['tipo'].widget.attrs['disabled'] = True

        contexto = {
            'title':' Meus Dados',
            'form': userForm,
            'usuarioForm': usuarioForm

        }
    return render(request, 'usuarios/pages/dados_usuario.html', contexto)

@login_required
def editar_usuario(request, id):
    if not request.user.is_authenticated:
        return redirect('login')
    
    if not isUserAdmin(request.user):
        messages.error(request, "Você não é administrador")
        return redirect('usuarios:lista_usuarios')

    user = get_object_or_404(User, pk = id)
    usuario = get_object_or_404(Usuario, user_id = user.id)
    
    if request.method == 'POST':
        form = UserUpdateForm(request.POST, instance=user)
        usuarioForm = UsuarioForm(request.POST, instance = usuario)
        
        if form.is_valid() and usuarioForm.is_valid():
            form.save()
            usuarioForm.save()
            messages.success(request, "Editado com sucesso")
            return redirect('usuarios:lista_usuarios')
        
        return render(request, 'usuarios/pages/editar_usuario.html', 
                { 'title':' Edição de Usuários',
                   'id': id,
                'form': form,
                'usuarioForm': usuarioForm
        })

    else:
        userForm = UserUpdateForm(instance = user)
        usuarioForm = UsuarioForm(instance = usuario)
        
        contexto = {
            'title':' Edição de Usuários',
            'id': id,
            'form': userForm,
            'usuarioForm': usuarioForm

        }
        return render(request, 'usuarios/pages/editar_usuario.html', contexto)

def usuario_teste(request):
    return render(request, 'usuarios/pages/usuario.html')




# usuario = Usuario.objects.select_related('user').get(pk=2)

apps/usuarios/templates/usuarios/pages/cadastro_usuario.html
{% extends "globals/base.html"%}

{% block content %}


        <!-- ?> -->
        {% include 'globals/partials/_alertas.html' %}

        <div class="row text-center mt-3">
            <br>
            <h3>Novo Usuário</h3>

        </div>
         
        <div class="container col-sm-10">
            
            <div class="row d-flex justify-content-center">
                <form method='post'>
                    {% csrf_token %}

                    <div class="form-group mt-1 mb-3 d-flex row ">
                        <div class="label-class col-sm-3 text-start text-sm-end">
                            <label class="col-form-label" for="{{ form.login.id_for_label}}">
                                {{form.login.label}}</label>
                        </div>
                        <div class="col-sm-8">
                            {{form.login}}
                            
                            {% if form.login.errors %}
                            <span style="color: red;" role="alert">
                                {{form.login.errors}}   
                            </span>
                            {% endif %}
                        </div>

                    </div>
                    
                    <div class="form-group mt-1 mb-3 d-flex row ">
                        <div class="label-class col-sm-3 text-start text-sm-end">
                            <label class="col-form-label" for="{{ form.nome.id_for_label}}">
                                {{form.nome.label}}</label>
                        </div>
                        <div class="col-sm-8">
                            {{form.nome}}
                            
                            {% if form.nome.errors %}
                            <span style="color: red;" role="alert">
                                {{form.nome.errors}}   
                            </span>
                            {% endif %}
                        </div>
                    </div>

                    <div class="form-group mt-1 mb-3 d-flex row ">
                        <div class="label-class col-sm-3 text-start text-sm-end">
                            <label class="col-form-label" for="{{ form.sobrenome.id_for_label}}">
                                {{form.sobrenome.label}}</label>
                        </div>
                        <div class="col-sm-8">
                            {{form.sobrenome}}
                            
                            {% if form.sobrenome.errors %}
                            <span style="color: red;" role="alert">
                                {{form.sobrenome.errors}}   
                            </span>
                            {% endif %}
                        </div>
                    </div>
                    

                    <div class="form-group mt-1 mb-3 d-flex row ">
                        <div class="label-class col-sm-3 text-start text-sm-end">
                            <label class="col-form-label" for="{{ form.email.id_for_label}}">
                                {{form.email.label}}</label>
                        </div>
                        <div class="col-sm-8">
                            {{form.email}}
                            {% if form.email.errors %}
                            <span style="color: red;" role="alert">
                                {{form.email.errors}}   
                            </span>
                            {% endif %}
                        </div>
                    </div>

                    <div class="form-group mt-3 mb-3 d-flex row ">
                        <div class="label-class col-sm-3 text-start text-sm-end">
                            <label class="col-form-label" for="{{ form.login.id_for_label}}">
                                {{form.senha.label}}</label>
                        </div>
                        <div class="col-sm-8">
                            {{form.senha}}
                            {% if form.senha.errors %}
                            <span style="color: red;" role="alert">
                                {{form.senha.errors}}   
                            </span>
                            {% endif %}
                            
                        </div>

                    </div>

                    <div class="form-group mt-3 mb-3 d-flex row ">
                        <div class="label-class col-sm-3 text-start text-sm-end">
                            <label class="col-form-label" for="{{ form.confirmacao_senha.id_for_label}}">
                                {{form.confirmacao_senha.label}}</label>
                        </div>
                        <div class="col-sm-8">
                            {{form.confirmacao_senha}}
                            {% if form.confirmacao_senha.errors %}
                            <span style="color: red;" role="alert">
                                {{form.confirmacao_senha.errors}}   
                            </span>
                            {% endif %}
                        </div>
                        
                    </div>

                    
                    <div class="form-group mt-3 mb-3 d-flex row ">
                        <div class="label-class col-sm-3 text-start text-sm-end">
                            <label class="col-form-label" for="{{ form.tipo_usuario.id_for_label}}">
                                {{form.tipo_usuario.label}}</label>
                        </div>
                        <div class="col-sm-8">
                            {{form.tipo_usuario}}
                            {% if form.tipo_usuario.errors %}
                            <span style="color: red;" role="alert">
                                {{form.tipo_usuario.errors}}   
                            </span>
                            {% endif %}
                        </div>
                        
                    </div>
                    
                    
                    <div class="d-grid justify-content-center m-2">
                        <button type="submit" class="btn btn-primary" > Cadastrar </button>
                    </div>
                </form>
            </div>
        

        </div>

{% endblock %}

apps/usuarios/templates/usuarios/pages/dados_usuario.html
{% extends "globals/base.html"%}

{% block content %}

{% include 'globals/partials/_alertas.html' %}

<br>
<div class="panel-heading">
    <h3 class="panel-title">{{ title }}</h3>
</div>

<div class="container col-sm-10">
    <br>

    <form action="{% url 'usuarios:dados_usuario' %}" method="post">
        {% csrf_token %}
        
        {% if form %}
            {% include 'globals/partials/_form.html' with form=form %}
        {% endif %}

        <div class="col d-flex justify-content-center">
            <button type="submit" class="btn btn-primary m-2" > Salvar </button>
        </div>

    
    </form>    
         
    </div>

</div>


{% endblock %}

apps/usuarios/templates/usuarios/pages/editar_usuario.html
{% extends "globals/base.html"%}

{% block content %}

{% include 'globals/partials/_alertas.html' %}

<br>
<div class="panel-heading">
    <h3 class="panel-title">{{ title }}</h3>
</div>

<div class="container col-10">
    <br>

    <form action="{% url 'usuarios:editar_usuario' id %}" method="post">
        {% csrf_token %}
        
        {% if form %}
            {% include 'globals/partials/_form.html' %}
        {% endif %}

        <div class=" d-flex justify-content-center m-2">
            <button type="submit" class="btn btn-primary m-2" > Salvar </button>
        </div>

    
    </form>    
         
    </div>

</div>
{% endblock %}

apps/usuarios/templates/usuarios/pages/lista_usuarios.html
{% extends "globals/base.html"%}

{% block content %}

{% include 'globals/partials/_alertas.html' %}

<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-info">
            <br>
            <div class="panel-heading">
                <h3 class="panel-title"> {{ titulo }}</h3>
            </div>

            <div class=" d-flex justify-content-end m-2">
                <a href="{% url 'usuarios:cadastro_usuario' %}">  
                        <button type="submit" class="btn btn-primary"> Novo Usuário</button>
                </a>
                
        
            </div>

            <div class="table-responsive table-sortable">

                <table class="table table-bordered table-striped">
                    <colgroup>
                        <col class="col-xs-3">
                        <col class="col-xs-2">
                        <col class="col-xs-2">
                    </colgroup>
                    <thead>
                        <tr>
                            <th>Login</th>
                            <th>Nome</th>
                            <th>Email</th>
                            <th>Tipo</th>
                            <th>Ações</th>
                        </tr>
                    </thead>
                    <tbody>

                        {% if forms  %}
                            {% for cliente in forms %}
                            
                                <tr>
                                    <td>{{ cliente.user.username}} </td>
                                    <td>{{ cliente.user.first_name}} {{ cliente.user.last_name}} </td>
                                    <td>{{ cliente.user.email }}</td>
                                    <td>{{ cliente.get_tipo_display }}</td>
                                    <td align="center">
                                        <span class="link me-2"><a href="{% url 'usuarios:editar_usuario' cliente.user.id %}" title="Editar"><i class="fa-solid fa-pen-to-square"></i></a></span>
                                        
                                    
                                        <span class="link ms-3">
                                            <a href="#" class="botao_modal"
                                            data-bs-toggle="modal"
                                            data-bs-target="#deletar_usuario_modal"
                                            data-id="{{ cliente.user.id }}"
                                            data-name="{{ cliente.user.username }}">
                                            <i class="fa-solid fa-trash"> </i>
                                            </a>
                                        </span>
                                    </td>

                    
                                </tr>
                                
                                {% include 'usuarios/partials/_deletar_usuario_modal.html' %}
                                {% endfor %}
                                
                        {% else %}    
                            
                            <tr>
                                <td colspan="8">Sem registros</td>
                            </tr>
                        
                        {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script>

    $('.botao_modal').click(function(){
        $('#building-id').html($(this).data('id'));
        $('#building-name').html($(this).data('name'));


        const formmodal = document.getElementById("form-modal")
        link = formmodal.action.split('/').slice(0,-1).join('/')+'/'+$(this).data('id')
        formmodal.action = link
        console.log(link)
        

    });

</script>
{% endblock %}

apps/usuarios/templates/usuarios/pages/login.html
{% load static %}
{% include 'globals/partials/_head.html' %}

<body>

    <div class="container text-center">

        <!-- head -->

        {% include 'orion/partials/_header.html' %}
        <!-- end head -->


        <!-- ?> -->
        {% include 'globals/partials/_alertas.html' %}

        <div class="row title-login">
            <div class="col">
                <h3> Entre com o seu Login e Senha</h3>
            </div>
        </div>  

                
        <div class="row d-flex justify-content-center m-3">
            <div class="col-sm-3 ">
                <form method='post'>
                    {% csrf_token %}
                    {{ form.as_p}}
                    <div class="d-grid">
                        <button type="submit" class="btn btn-primary" name = "btn_login" > Login </button>
                    </div>
                </form>
            </div>
        </div>

 
        <!--  conteudo  -->
            
        {% block content %}
        {% endblock %}


        {% include 'globals/partials/_footer.html' %}
    </div>

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>


</body>

</html>

apps/usuarios/templates/usuarios/pages/usuario.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1> usuario template </h1>
</body>
</html>