apps/orion/urls.py
from django.urls import path

from apps.orion import views

app_name = 'orion'

urlpatterns = [
     path('', views.ChamadoHomeList.as_view(), name='lista_home'),
     path('chamados/', views.ChamadoList.as_view(), name='lista_chamados'),
     path('chamados/busca/', views.busca_chamados, name='busca_chamados'),
     path('chamados/fechados/', views.ChamadosFechadosList.as_view(), name='chamados_fechados'),
     path('chamado/fechar/<int:id>/', views.fechar_chamado, name='fechar_chamado'),
     path('chamado/novo/', views.novo_chamado, name='novo_chamado'),
     path('chamado/editar/<int:id>/', views.editar_chamado, name='editar_chamado'),
     path('chamado/deletar/<int:id>/', views.deletar_chamado, name='deletar_chamado'),


     path('carga_horaria/editar/<int:id>/', views.editar_carga_horaria, name = 'editar_carga_horaria'),
     path('nova_carga_horaria', views.nova_carga_horaria, name = 'nova_carga_horaria'),
     
     
     path('equipamentos/', views.EquipamentoList.as_view(), name='equipamentos'),
     path('equipamentos/<int:id>/', views.EquipamentoDetail.as_view(),name='detalhar_equipamento'),
     path('equipamentos_select2/<int:id>/', views.equipamentos_select2, name='equipamentos_select2'),
     path('equipamentos/novo', views.EquipamentoDetail.as_view(), name='cadastrar_equipamentos'),
     
     path('equipamentos/deletar/<int:id>/', views.EquipamentoDelete.as_view(), name='deletar_equipamento'),
     
     path('empresas/', views.empresas, name='empresas'),
     path('empresas/<int:id>/', views.detalhar_empresa, name='detalhar_empresa'),
     path('empresas/deletar/', views.deletar_empresa, name='deletar_empresa'),
     path('empresas/nova/', views.cadastrar_empresa, name='cadastrar_empresa'),
     
     path('assinatura_popup', views.assinatura_popup, name='assinatura_popup'),
     path('marcar_notificacao_como_lida', views.marcar_notificacao_como_lida, name = "marcar_notificacao_como_lida"),
     path('relatorio_ponto', views.relatorio_ponto, name = "relatorio_ponto"),
     path('download/', views.download_file, name='download_file'),
     path('teste', views.teste, name='teste'),
     path('list_teste', views.list_teste, name='list_teste'),

]

orion/urls.py
from django.urls import path

from orion import views

app_name = 'orion'

urlpatterns = [
     path('', views.lista_home, name='lista_home'),
     path('chamados/', views.lista_chamados, name='lista_chamados'),
     path('chamados/busca/', views.busca_chamados, name='busca_chamados'),
     path('chamados_fechados/', views.chamados_fechados, name='chamados_fechados'),
     path('fechar_chamado/<int:id>/', views.fechar_chamado, name='fechar_chamado'),
     path('chamados/<int:id>/', views.novo_chamado_view, name='novo_chamado_view'),
     path('novo_chamado/', views.novo_chamado, name='novo_chamado'),
     path('editar_chamado/<int:id>/', views.editar_chamado, name='editar_chamado'),
     path('deletar_chamado/<int:id>/', views.deletar_chamado, name='deletar_chamado'),
     path('equipamentos/', views.equipamentos, name='equipamentos'),
     path('equipamentos/<int:id>/', views.detalhar_equipamento,name='detalhar_equipamento'),
     path('equipamentos_select2/<int:id>/', views.equipamentos_select2, name='equipamentos_select2'),
          
     path('cadastrar_equipamentos/', views.cadastrar_equipamentos,
          name='cadastrar_equipamentos'),
     path('deletar_equipamento/<int:id>/',
          views.deletar_equipamento, name='deletar_equipamento'),
     path('clientes/', views.clientes, name='clientes'),
     path('clientes/<int:id>/', views.detalhar_cliente, name='detalhar_cliente'),
     path('deletar_cliente/',
          views.deletar_cliente, name='deletar_cliente'),
     path('cadastrar_clientes/', views.cadastrar_clientes, name='cadastrar_clientes'),
     path('assinatura_popup', views.assinatura_popup, name='assinatura_popup'),
     path('marcar_notificacao_como_lida', views.marcar_notificacao_como_lida, name = "marcar_notificacao_como_lida"),
     path('relatorio_ponto', views.relatorio_ponto, name = "relatorio_ponto"),
     path('download/', views.download_file, name='download_file'),
     path('teste', views.teste, name='teste'),
     path('list_teste', views.list_teste, name='list_teste'),

]

setup/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.orion.urls')),
    path('', include('apps.usuarios.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/orion/models.py
from datetime import datetime, time

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from jsignature.fields import JSignatureField

from apps.usuarios.models import Usuario

#from smart_selects.db_fields import ChainedForeignKey


# from validate_docbr import CPF

# Create your models here.


class Endereco(models.Model):
    rua = models.CharField(max_length=100)
    numero = models.IntegerField()
    bairro = models.CharField(max_length=50)
    cep = models.CharField(max_length=8)
    uf = models.CharField(max_length=2)
    cidade = models.CharField(max_length=100)
    complemento = models.CharField(max_length=100, blank=True, null=True)
    def __str__(self):
        return f'{self.rua}, {self.numero} - {self.bairro}, {self.cidade}-{self.uf}, {self.cep}'


class Empresa (models.Model):
    nome       = models.CharField(max_length=100)
    cnpj       = models.CharField(max_length=14)
    telefone   = models.CharField(max_length=14, null=True, blank=True)
    email      = models.CharField(max_length=35,null=True, blank=True)
    observacao = models.CharField(max_length=280, null=True, blank=True)#
    endereco   = models.OneToOneField(Endereco, on_delete=models.SET_NULL, 
                                      null=True, blank=True, related_name='empresa')

    
    def __str__(self):
        return f'{self.nome}'


class Equipamento(models.Model):
    empresa          = models.ForeignKey(Empresa, on_delete=models.SET_NULL, related_name='equipamento', null=True, blank=True)
    numero_serie     = models.CharField(max_length=100)
    equipamento      = models.CharField(max_length=100)
    tipo_equipamento = models.CharField(max_length=35)
    descricao        = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return f'{self.equipamento}'


class TIPO_STATUS(models.TextChoices):
    PARADO = 'P', _('Parado')
    RESTRITO = 'R', _('Restrito')
    NORMAL = 'N', _('Normal')
    OUTROS = 'O', _('Outros')


class Chamado(models.Model):
    TIPO_DE_CHAMADO = (('C', 'Contrato'), ('A', 'Avulso'))
    
    STATUS_CHAMADO = (('A', 'Aberto'), ('F', 'Fechado'))
    
    status = models.CharField(
        max_length=1, choices=TIPO_STATUS.choices, blank=False, null=False, default='P')
    
    tipo_chamado = models.CharField(
        max_length=1, choices=TIPO_DE_CHAMADO, blank=False, null=False, default='C')

    status_chamado = models.CharField(
        max_length=1, choices=STATUS_CHAMADO, default='A')

    numero_chamado = models.CharField(max_length=14)  # YYYY DD MM HHHH SS
    descricao_chamado = models.CharField(max_length=150, blank=False)
    descricao_servico = models.TextField(null=True, blank=True)
    observacoes_do_cliente = models.TextField(blank=True, null = True)
    criado_em = models.DateTimeField(auto_now_add=True)
    atualizado_em = models.DateTimeField(auto_now=True)

    empresa = models.ForeignKey(
        Empresa, on_delete=models.SET_NULL, related_name='ordem_servico', null=True, blank=True)

    equipamento = models.ForeignKey(Equipamento, on_delete=models.SET_NULL, null=True, blank=True)

    contato = models.CharField(max_length=100, null=True, blank=True)
    
    aberto_por = models.ForeignKey(
        Usuario, on_delete=models.SET_NULL, null=True, related_name='ordem_servico')

    assinatura = JSignatureField(null=True, blank=True)
    
    def __str__(self):
        return f'Status = {self.status}, Tipo de chamado - {self.tipo_chamado}, - Criado em {self.criado_em}'

    def get_absolute_url(self):
        return reverse("orion:editar_chamado", args=(self.pk,))
    

class CargaHoraria(models.Model):
    data = models.DateField()
    hora_inicio = models.TimeField()
    hora_termino = models.TimeField()
    horas_de_trabalho = models.TimeField()
    status = models.CharField(
        max_length=1, choices=TIPO_STATUS.choices, blank=False, null=False, default='N')
    tecnico = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='carga_horaria')

    ordem_servico = models.ForeignKey(
        Chamado, on_delete=models.SET_NULL, null=True, related_name='carga_horaria')

    def __str__(self):
        return f'dia = {self.data} -Entrada =  {self.hora_inicio} -Saida =  {self.hora_termino}'

    def save(self, *args, **kwargs):
        # Convertendo cada objeto datetime.time em um objeto datetime
        hora_inicio = datetime.combine(self.data, self.hora_inicio)
        hora_termino = datetime.combine(self.data, self.hora_termino)
        
        # Calcule a diferença entre os dois horarios
        diferenca = hora_termino - hora_inicio
        
        diferenca_horas, diferenca_segundos = divmod(diferenca.seconds, 3600)
        diferenca_minutos, _ = divmod(diferenca_segundos, 60)
        #horas trabalhadas
        self.horas_de_trabalho= time(hour=diferenca_horas, minute=diferenca_minutos, second=0)
        super(CargaHoraria, self).save(*args, **kwargs)


class TIPO_DESPESA(models.TextChoices):
    ALIMENTACAO = 'AL', _('Alimentação')
    BAGAGEM = 'BA', _('Bagagem')
    ALUGUEL_CARROS = 'AC', _('Aluguel de carros')
    COMBUSTIVEL = 'CO', _('Combustível')
    CORREIO_FRETE = 'CF', _('Correio/Frete')
    ESTACIONAMENTO = 'ES', _('Estacionamento')
    FRIGOBAR = 'FR', _('Friogobar')
    HOSPEDAGEM = 'HO', _('Hospedagem')
    LAVANDERIA = 'LA', _('Lavanderia')
    COMPRA_DE_MATERIAL = 'CM', _('Compra de material')
    PAGAMENTOS = 'PG', _('Pagamentos')
    PASSAGEM_AERIA = 'PA', _('Passagem Aéria')
    TRANSPORTE = 'TR', _('Transporte')
    OUTROS = 'OT', _('Outros')

class Despesa(models.Model):
    tipo = models.CharField(
        max_length=2, choices=TIPO_DESPESA.choices, blank=False, null=False, default='AL')
    data = models.DateField()
    valor = models.DecimalField(max_digits=10, decimal_places=2)
    tecnico = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='despesa')
    ordem_servico = models.ForeignKey(Chamado, on_delete=models.SET_NULL, null=True, related_name='despesa')

    def __str__(self):
        return f'tipo = {self.tipo} -data =  {self.data} - valor =  {self.valor}'


class SignatureModel(models.Model):
    signature = JSignatureField()

apps/orion/views/chamado.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import ListView

from apps.orion import utils
from apps.orion.models import Chamado
from apps.usuarios.models import Usuario


@method_decorator(login_required(login_url='usuarios:login' ,redirect_field_name='next'), name='dispatch' )
class ChamadoList(ListView):
    model = Chamado
    context_object_name = "chamados"
    template_name = 'orion/pages/chamado_list.html'
    
    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        
        qs = qs.select_related('empresa', 'equipamento').filter(status_chamado='A').order_by('-id')
        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        chamado_page = utils.paginacao(self.request, ctx.get('chamados'))
        ctx.update({'chamados': chamado_page })
        ctx['titulo'] = f'Chamados abertos'
        return ctx
    
@method_decorator(login_required(login_url='usuarios:login' ,redirect_field_name='next'), name='dispatch' )
class ChamadoHomeList(ChamadoList):

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        usuario = Usuario.objects.get(user_id=self.request.user.id)
        qs = qs.filter(aberto_por=usuario)
        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        ctx['home'] = f'Olá, {self.request.user.username.title()}'
        return ctx
    
@method_decorator(login_required(login_url='usuarios:login' ,redirect_field_name='next'), name='dispatch' )
class ChamadosFechadosList(ChamadoList):

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        
        qs = Chamado.objects.all().select_related('empresa', 'equipamento').filter(
        status_chamado='F').order_by('-id')
        return qs
    
    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        ctx['titulo'] = f'Chamados fechados'
        return ctx

apps/orion/views/equipamento.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.http.response import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import ListView

from apps.orion import utils
from apps.orion.forms import EquipamentosForm
from apps.orion.models import Equipamento


@login_required
def equipamentos_select2(request, id):
    dados = Equipamento.objects.filter(empresa=id)
    dados_json = [{'id': d.id, 'nome': d.equipamento} for d in dados]
    return JsonResponse(dados_json, safe=False)

@method_decorator(login_required(login_url='usuarios:login' ,redirect_field_name='next'), name='dispatch' )
class EquipamentoList(ListView):
    model = Equipamento
    context_object_name = "equipamentos"
    template_name = 'orion/pages/equipamentos.html'
    ordering = '-id'
    
    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.select_related('empresa')
        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        equipamento_page = utils.paginacao(self.request, ctx.get('equipamentos'))
        ctx.update({'equipamentos': equipamento_page })
        return ctx

@method_decorator(login_required(login_url='usuarios:login' ,redirect_field_name='next'), name='dispatch' )
class EquipamentoDetail(View):
    
    def get_equipamento(self, id):
        equipamento = None
        if id:  
            equipamento = get_object_or_404(Equipamento, pk=id )

        return equipamento
         

    def render_equipamento(self, form, id ):
        return render(self.request, 'orion/pages/detalhes_equipamentos.html', { 'form': form, 'id': id})

    def get(self, request, id=None):
        equipamento = self.get_equipamento(id)
        equipamentoForm = EquipamentosForm(instance=equipamento)
        return self.render_equipamento(equipamentoForm, id)

    def post(self, request, id=None):
        equipamento = self.get_equipamento(id)
        equipamentoForm = EquipamentosForm(self.request.POST, instance=equipamento)
        
        if equipamentoForm.is_valid():
            messages.success(self.request, "Equipamento Salvo com Sucesso")
            equipamentoForm.save()
            return redirect('orion:equipamentos')
        else:
            return self.render_equipamento(equipamentoForm, id)
            
@method_decorator(login_required(login_url='usuarios:login' ,redirect_field_name='next'), name='dispatch' )
class EquipamentoDelete(EquipamentoDetail):
    def post(self, request, id=None):
        #post(self, *args, **kwargs): self.request.POST.get('id')
        equipamento = self.get_equipamento(id)
        equipamento.delete()
        messages.success(self.request, "Equipamento deletado com sucesso")
        return redirect('orion:equipamentos')

apps/orion/templates/orion/partials/_assinatura-popup.html
<!DOCTYPE html>
{% load jsignature_filters %}
{% load static %}
{% load widget_tweaks %}

<html lang="pt-br">

    <head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
   
    <title>Orion - Sistema de Atendimento ao Cliente </title>
    <style>
        * {
            padding: 0;
            margin: 0;
            box-sizing: border-box;


        }

        html {
            font-size: 62, 5%;

        }

        body {
            background: #E8F3FF;
            height: 300px;
            width: 800px;
        }

        .hidden{
            display:none;
        }
        button {
            padding: 0.4rem;
        }


        .container {
            padding-right: 15px;
            padding-left: 15px;
            margin-right: auto;
            margin-left: auto;
            background: #FFF;
            max-width: 75rem;
        }


    </style>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="/path/to/select2.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@ttskch/select2-bootstrap4-theme@x.x.x/dist/select2-bootstrap4.min.css">


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    </head>

    <body>    
        
        <div class="container col-8 justify-content-center ms-5">

            <button id="reset-button" type="button">Limpar Assinatura</button>
            <button onclick = 'window.close()' type="button">Salvar </button>
            <div id = "assinatura">
                {{ form.media }}
                {{ form.signature }}
            </div>
            
        </div>


        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        
    </body>
    <script>

        $(document).ready(function() {
            $('#reset-button').click(function(){
                $('#jsign_signature').jSignature("reset");
            });  
        });
        
        
    </script>

    
   <script src="{% static 'js/jSignature.min.js' %}"></script>
   <!-- <script src="{% static 'js/django_jsignature.js' %}"></script>
   -->
</html>

apps/orion/templates/orion/partials/_carga_horaria_error_modal.html
{% load static %}

<!-- Modal -->
<div class="modal fade" id="error_ch_Modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
        <h1 class="modal-title fs-5" >Erro ao Adicionar Hora</h1>
        </div>
        <div class="modal-body">
            <p>Já existe um Horario Cadastrado ou Hora de Inicio é Maior que a hora de Termino</p>
        </div>

        <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
       

        </div>
    </div>
    </div>
</div>
<!-- End Modal -->

apps/orion/templates/orion/partials/_carga_horaria_form.html
<tr>
    <td>{{ form_ch.data }}</td>
    <td>{{ form_ch.hora_inicio }}</td>
    <td>{{ form_ch.hora_termino }}</td>
    <td>
        <input type="hidden" name="id" value="{{id}}">
    </td>
    <td colspan="2">
        {{ form_ch.status }} 
    </td>
    <td align="center">
        <div class="d-grid gap-2 d-flex justify-content-center">

            <button class="btn btn-success" 
            hx-post= {% if link %} "{{ link }}" {% else %} "{% url 'orion:nova_carga_horaria' %}" {% endif %}
            hx-include="closest tr"
            hx-trigger='click'
            hx-target="closest tr"
            hx-swap="outerHTML">
            <i class="fa-regular fa-floppy-disk"></i>
            <span class="my-indicator">
                <i class=" fa-solid fa-spinner fa-spin"></i>
            </span>
        </button> 
        
        <button class="btn btn-warning" 
        hx-confirm="Você tem certeza?"
        hx-delete={% if link %} "{{ link }}" {% else %} "{% url 'orion:nova_carga_horaria' %}" {% endif %}
        hx-target="closest tr" 
        hx-swap="outerHTML swap:1s"
        >
        
            <i class="fa-solid fa-xmark"></i>
            <span class="my-indicator">
                <i class=" fa-solid fa-spinner fa-spin"></i>
            </span>
        </button>
    </div>
    </td>
<tr>

apps/orion/templates/orion/partials/_carga_horaria_obj.html
<tr class="table-success">
    <td>{{ ch.data|date:"d/m/Y"}}</td>
    <td>{{ ch.hora_inicio}}</td>
    <td>{{ ch.hora_termino}}</td>
    <td>{{ ch.horas_de_trabalho}}</td>
    <td>{{ ch.tecnico}}</td>
    <td>{{ ch.get_status_display}}</td>
    
    
    
    <td align="center">
        <a  href="#"
        hx-get="{% url 'orion:editar_carga_horaria' ch.id %}" 
        hx-include="closest tr"
        hx-trigger='click'
        hx-target="closest tr"
        hx-swap="outerHTML"
        >
        <i class="fa-solid fa-pen-to-square"></i>
        </a>
    </td>
</tr>

apps/orion/templates/orion/partials/_confirmacao_modal.html
{% load static %}

{% comment %}
{% include 'orion/partials/_confirmacao_modal.html' with id_modal="cancelar-modal" acao="Cancelar Edição do" %}
{% endcomment %}
<div class="modal" tabindex="-1" id={{ id_modal }}>
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"> {{ acao }} chamado </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" >
                
                {{info_extra}}
                <p>Você tem certeza ? <p>
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                <button type="submit" class="btn btn-danger" >Confirmar</button>
            </div>
        </div>
    </div>
</div>

apps/orion/templates/orion/partials/_header.html
<header role="banner" class="head ">
    <div class="row">
        <div class="col">
            <div class="topo">
                <h2>Orion - Sistema de Atendimento ao Cliente</h2>
            </div>
        </div>
    </div>
</header>

apps/orion/templates/orion/partials/_lista_chamados.html
<table class="table-sortable table table-bordered table-striped">
    <colgroup>
        <col class="col-xs-3">
        <col class="col-xs-2">
        <col class="col-xs-2">
        <col class="col-xs-1">
        <col class="col-xs-1">
        <col class="col-xs-1">
        <col class="col-xs-1">
    </colgroup>
    <thead>
        <tr>
            <th>Chamado</th>
            <th>Cliente</th>
            <th>Equipamento</th>
            <th>Tipo</th>
            <th>Data</th>
            <th>Status</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>

            {% for chamado in chamados %}
            
                <tr>
                    <td>{{chamado.numero_chamado}} - {{ chamado.descricao_chamado }} </td>
                    <td>{{chamado.empresa}} </td>
                    <td>{{chamado.equipamento.numero_serie}} - {{chamado.equipamento}}</td>
                    <td> {{ chamado.get_tipo_chamado_display }} </td>
                    <td>{{chamado.criado_em|date:"d/m/Y"}}</td>
                    <td>{{ chamado.get_status_display }} - {{ chamado.get_status_chamado_display }}

                    </td>
                    <td align="center"><a href="{% url 'orion:editar_chamado' chamado.id %}" title="Editar"><i
                        class="fa-solid fa-pen-to-square"></i></a></td>
                </tr>
            {% empty %}
                
                <tr>
                    <td colspan="8">Sem registros</td>
                </tr>
                
            {% endfor %}
            
    </tbody>
</table>

apps/orion/templates/orion/partials/_lista_clientes.html
<table class="table table-bordered table-striped">
    <colgroup>
        <col class="col-xs-3">
        <col class="col-xs-2">
        <col class="col-xs-2">
        <col class="col-xs-1">
        <col class="col-xs-1">
        <col class="col-xs-2">
    </colgroup>
    <thead>
        <tr>
            <th>Nome</th>
            <th>CNPJ</th>
            <th>Telefone</th>
            <th>Email</th>
            <th>Estado</th>
            <th>Observação</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>


            {% for cliente in clientes %}
            
                <tr>
                    <td>{{ cliente.nome}} </td>
                    <td>{{ cliente.cnpj}} </td>
                    <td>{{ cliente.telefone}} </td>
                    <td>{{ cliente.email }}</td>
                    <td>{{ cliente.endereco.uf }}</td>
                    <td>{{ cliente.observacao }} </td>
                    <td align="center"><a href="{% url 'orion:detalhar_cliente' cliente.id %}" title="Editar"><i
                        class="fa-solid fa-pen-to-square"></i></a></td>
                </tr>
                
            {% empty %}    
                    
                <tr>
                    <td colspan="8">Sem registros</td>
                </tr>
            {% endfor %}
    </tbody>
</table>

apps/orion/templates/orion/partials/_lista_empresas.html
<table class="table table-bordered table-striped">
    <colgroup>
        <col class="col-xs-3">
        <col class="col-xs-2">
        <col class="col-xs-2">
        <col class="col-xs-1">
        <col class="col-xs-1">
        <col class="col-xs-2">
    </colgroup>
    <thead>
        <tr>
            <th>Nome</th>
            <th>CNPJ</th>
            <th>Telefone</th>
            <th>Email</th>
            <th>Estado</th>
            <th>Observação</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>


            {% for empresa in empresas %}
            
                <tr>
                    <td>{{ empresa.nome}} </td>
                    <td>{{ empresa.cnpj}} </td>
                    <td>{{ empresa.telefone}} </td>
                    <td>{{ empresa.email }}</td>
                    <td>{{ empresa.endereco.uf }}</td>
                    <td>{{ empresa.observacao }} </td>
                    <td align="center"><a href="{% url 'orion:detalhar_empresa' empresa.id %}" title="Editar"><i
                        class="fa-solid fa-pen-to-square"></i></a></td>
                </tr>
                
            {% empty %}    
                    
                <tr>
                    <td colspan="8">Sem registros</td>
                </tr>
            {% endfor %}
    </tbody>
</table>