apps/orion/urls.py
from django.urls import path

from apps.orion import views

app_name = 'orion'

urlpatterns = [
     path('', views.ChamadoHomeList.as_view(), name='lista_home'),
     path('chamados/', views.ChamadoList.as_view(), name='lista_chamados'),
     path('chamados/busca/', views.busca_chamados, name='busca_chamados'),
     path('chamados/fechados/', views.ChamadosFechadosList.as_view(), name='chamados_fechados'),
     path('chamado/fechar/<int:id>/', views.fechar_chamado, name='fechar_chamado'),
     path('chamado/novo/', views.novo_chamado, name='novo_chamado'),
     path('chamado/editar/<int:id>/', views.editar_chamado, name='editar_chamado'),
     path('chamado/deletar/<int:id>/', views.deletar_chamado, name='deletar_chamado'),


     path('carga_horaria/editar/<int:id>/', views.editar_carga_horaria, name = 'editar_carga_horaria'),
     path('nova_carga_horaria', views.nova_carga_horaria, name = 'nova_carga_horaria'),
     
     
     path('equipamentos/', views.EquipamentoList.as_view(), name='equipamentos'),
     path('equipamentos/<int:id>/', views.EquipamentoDetail.as_view(),name='detalhar_equipamento'),
     path('equipamentos_select2/<int:id>/', views.equipamentos_select2, name='equipamentos_select2'),
     path('equipamentos/novo', views.EquipamentoDetail.as_view(), name='cadastrar_equipamentos'),
     
     path('equipamentos/deletar/<int:id>/', views.EquipamentoDelete.as_view(), name='deletar_equipamento'),
     
     path('empresas/', views.empresas, name='empresas'),
     path('empresas/<int:id>/', views.detalhar_empresa, name='detalhar_empresa'),
     path('empresas/deletar/', views.deletar_empresa, name='deletar_empresa'),
     path('empresas/nova/', views.cadastrar_empresa, name='cadastrar_empresa'),
     
     path('assinatura_popup', views.assinatura_popup, name='assinatura_popup'),
     path('marcar_notificacao_como_lida', views.marcar_notificacao_como_lida, name = "marcar_notificacao_como_lida"),
     path('relatorio_ponto', views.relatorio_ponto, name = "relatorio_ponto"),
     path('download/', views.download_file, name='download_file'),
     path('teste', views.teste, name='teste'),
     path('list_teste', views.list_teste, name='list_teste'),

]

apps/usuarios/urls.py
from django.urls import path

from . import views

app_name = 'usuarios'

urlpatterns = [
    path('usuarios/', views.lista_usuarios, name='lista_usuarios'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('cadastro_usuario/', views.cadastro_usuario, name='cadastro_usuario'),
    path('deletar_usuario/<int:id>', views.deletar_usuario, name='deletar_usuario'),
    path('dados-usuario/', views.dados_usuario, name='dados_usuario'),
    path('editar-usuario/<int:id>', views.editar_usuario, name='editar_usuario'),
    path('usuario_teste/', views.usuario_teste, name='usuario_teste'),
]

orion/urls.py
from django.urls import path

from orion import views

app_name = 'orion'

urlpatterns = [
     path('', views.lista_home, name='lista_home'),
     path('chamados/', views.lista_chamados, name='lista_chamados'),
     path('chamados/busca/', views.busca_chamados, name='busca_chamados'),
     path('chamados_fechados/', views.chamados_fechados, name='chamados_fechados'),
     path('fechar_chamado/<int:id>/', views.fechar_chamado, name='fechar_chamado'),
     path('chamados/<int:id>/', views.novo_chamado_view, name='novo_chamado_view'),
     path('novo_chamado/', views.novo_chamado, name='novo_chamado'),
     path('editar_chamado/<int:id>/', views.editar_chamado, name='editar_chamado'),
     path('deletar_chamado/<int:id>/', views.deletar_chamado, name='deletar_chamado'),
     path('equipamentos/', views.equipamentos, name='equipamentos'),
     path('equipamentos/<int:id>/', views.detalhar_equipamento,name='detalhar_equipamento'),
     path('equipamentos_select2/<int:id>/', views.equipamentos_select2, name='equipamentos_select2'),
          
     path('cadastrar_equipamentos/', views.cadastrar_equipamentos,
          name='cadastrar_equipamentos'),
     path('deletar_equipamento/<int:id>/',
          views.deletar_equipamento, name='deletar_equipamento'),
     path('clientes/', views.clientes, name='clientes'),
     path('clientes/<int:id>/', views.detalhar_cliente, name='detalhar_cliente'),
     path('deletar_cliente/',
          views.deletar_cliente, name='deletar_cliente'),
     path('cadastrar_clientes/', views.cadastrar_clientes, name='cadastrar_clientes'),
     path('assinatura_popup', views.assinatura_popup, name='assinatura_popup'),
     path('marcar_notificacao_como_lida', views.marcar_notificacao_como_lida, name = "marcar_notificacao_como_lida"),
     path('relatorio_ponto', views.relatorio_ponto, name = "relatorio_ponto"),
     path('download/', views.download_file, name='download_file'),
     path('teste', views.teste, name='teste'),
     path('list_teste', views.list_teste, name='list_teste'),

]

setup/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.orion.urls')),
    path('', include('apps.usuarios.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/globals/partials/_alertas.html
{% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}" role="alert">
        <p> {{ message }}</p>
    </div>
    {% endfor %}
{% endif %}

templates/globals/partials/_footer.html
{% block content %}

<footer class="rodape" role="contentinfo">
    <hr class="bg-info">
    <p> Orion - Sistema de Atendimento ao Cliente</p>
    <p>&copy; 2022 </p>
</footer>

{% endblock content %}

templates/globals/partials/_form.html
{% load widget_tweaks %}

{% for field in form.visible_fields %}

    <div class="form-group mt-3 mb-3 d-flex row">
        <div class="label-class col-sm-2 text-start text-sm-end">
            <label class="col-form-label " for="{{ field.id_for_label}}">
                {{field.label}}</label>
        </div>
        <div class="d-inline-flex flex-row col-sm-8">
            
            {{field|add_class:'form-control'}}
            
            
            {% if field.name == 'cep' %}
                <button id='buscaCep' name="buscaCepModal" class='btn btn-outline-secondary flex-shrink-0 pe-1 ms-1'>Buscar <i class="fa-solid fa-magnifying-glass"></i> </button>
            {% endif %}

            {% if field.errors %}
            <span style="color: red;" role="alert">
                {{field.errors}}   
            </span>
            {% endif %}
        </div>
        <small class="form-text text-muted d-flex justify-content-center">{{ field.help_text }}</small>
    </div>
{% endfor %}

templates/globals/partials/_head.html
{% load static %}

{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/fontawesome.min.css"
        integrity="sha512-giQeaPns4lQTBMRpOOHsYnGw1tGVzbAIHUyHRgn7+6FmiEgGGjaG0T2LZJmAPMzRCl+Cug0ItQ2xDZpTmEc+CQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/brands.min.css"
        integrity="sha512-G/T7HQJXSeNV7mKMXeJKlYNJ0jrs8RsWzYG7rVACye+qrcUhEAYKYzaa+VFy6eFzM2+/JT1Q+eqBbZFSHmJQew=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/solid.min.css"
        integrity="sha512-6mc0R607di/biCutMUtU9K7NtNewiGQzrvWX4bWTeqmljZdJrwYvKJtnhgR+Ryvj+NRJ8+NnnCM/biGqMe/iRA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    {# Include jQuery #}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    
    {# Include select2 #}
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@ttskch/select2-bootstrap4-theme@x.x.x/dist/select2-bootstrap4.min.css">
     
    {# Django Tempus Dominus assets are included in `{{ form.media }}` #}
    {{ form.media }}

    <!-- HTMX -->
    <script src="https://unpkg.com/htmx.org@1.9.2" integrity="sha384-L6OqL9pRWyyFU3+/bjdSri+iIphTN/bvYyM37tICVyOJkWZLpP2vGn6VUEXgzg6h" crossorigin="anonymous"></script>
    <meta name="htmx-config" content='{"includeIndicatorStyles": false}'>

    <title>Orion - Sistema de Atendimento ao Cliente </title>
    <style>
{% comment %}         /* HTMX
        #indicator{
            justify-content: center;
            color:var(--color-primary);
            position: relative;
            margin: 0 50%; 
            z-index: 5;
          }
    
          .htmx-indicator{
            opacity:0;
            transition: opacity 500ms ease-in;
          }
          .htmx-request .htmx-indicator{
              opacity:1
          }
         HTMX */ {% endcomment %}
        
        .my-indicator{
            display:none;
        }
        .htmx-request .my-indicator{
            display:inline;
        }
        .htmx-request.my-indicator{
            display:inline;
        }

        tr.htmx-swapping td {
            opacity: 0;
            transition: opacity 1s ease-out;
        }
        
         :root {
            --color-primary: #269fe6;
            --color-primary-hover: #2086c2;
            --color-primary-dark: #13141f;
            --color-primary-dark-hover: #212336;
            --color-primary-light: #d4ecfa;
            --color-primary-light-hover: #bdd8e7;

            --color-white: #fff;
            --color-black: #000;

            --color-dark-text: #444;
            --color-info-light: #cce5ff;
            --color-debug-light: #cce5ff;
            --color-success-light: #d4edda;
            --color-alert-light: #fff3cd;
            --color-warning-light: #fff3cd;
            --color-error-light: #f8d7da;

            --color-info-dark: #4d86c4;
            --color-debug-dark: #4d86c4;
            --color-success-dark: #4a9c5d;
            --color-alert-dark: #927f40;
            --color-warning-dark: #927f40;
            --color-error-dark: #da525d;

            --color-gray-0: #f9f9f9;
            --color-gray-1: #e0e0e0;
            --color-gray-2: #c7c7c7;
            --color-gray-3: #aeaeae;
            --color-gray-4: #959595;
            --color-gray-5: #7d7d7d;
            --color-gray-6: #646464;
            --color-gray-7: #4b4b4b;
            --color-gray-8: #323232;
            --color-gray-9: #191919;

            --font-primary: sans-serif;
            --font-headings: 'Roboto Slab', serif;

            --spacing-gutter-medium: 3rem;
            --spacing-gutter-large: 4rem;
        }

        * {
            padding: 0;
            margin: 0;
            box-sizing: border-box;
        }

        html {
            font-size: 62, 5%;

        }

        body {
            background: #E8F3FF;
        }
        
        .hidden{
            display:none;
            justify-content: center!important;
            padding: 0.5rem;
            margin: 0;
            box-sizing: border-box;
        }
        .repetir{
            justify-content: center!important;
            display: flex!important;
            padding: 0.5rem;
            
            box-sizing: border-box;"
        }

        .datetimefield{
            margin-left: 10px;
            margin-right: 25px;
            width: 140px;
        }
        
        .timefield{
            margin-left: 10px;
            margin-right: 25px;
            width: 105px;
        }
        
        .topo {
            background-image: url({% static 'orion/img/capa.jpg' %});
            background-repeat: no-repeat;
            background-size: cover;
            height: 20vh;
            color: #004080;
            text-shadow: 2px 2px #c4e1ff;
            text-align: center;
            font-size: 2.0vw;
            padding: 1rem;
        }

        .container {
            padding-right: 15px;
            padding-left: 15px;
            margin-right: auto;
            margin-left: auto;
            background: #FFF;
            max-width: 75rem;
        }

        #conteudo h4 {
            text-align: center;
            margin-top: 2rem;
        }


        .rodape p {
            text-align: center;
        }

        .nav2 {
            color: #337ab7;
        }
        .card-dados-titulo{

            background:#dff0d8;
            padding:0.4rem;
        }
        .dados-titulo{
            margin-left: 1rem;
            margin-top: 0.4rem;
            font-family: inherit;
            font-weight: 400;
            line-height: 1.1;
            color: #3C763B;
            font-size: 1rem;
        }
        .card-atendimento-titulo{

            background:#d9edf7;
            padding:0.4rem;
            border-color: #bce8f1;
        }
        .atendimento-titulo{
            margin-left: 1rem;
            margin-top: 0.4rem;
            font-family: inherit;
            font-weight: 400;
            line-height: 1.1;
            color: #31708f;
            font-size: 1rem;
        }

        .card-assinatura-titulo{

            background-color: #fcf8e3;
            padding:0.4rem;
            border-color: #faebcc;
        }
        .assinatura-titulo{
            margin-left: 1rem;
            margin-top: 0.4rem;
            font-family: inherit;
            font-weight: 400;
            line-height: 1.1;
            color: #8a6d3b;
            font-size: 1rem;
        }


        .title-login{
            margin-top: 2em;

        }
        .botao_modal{
            border:none;
        }
        .assinatura{
            border-style: ridge;
            border-radius:2%;
        }
        .notification {
            position: relative;
            display: inline-block;
          }
        
        
        .notification .badge {
            position: absolute;
            top: -10px;
            right: -10px;
            padding: 5px 10px;
            border-radius: 50%;
            background: red;
            color: white;
        }

        .notification-container {
            position: fixed;
            top: 80px;
            right: 20px;
            width: 350px;
            max-height: 400px;
            background-color: #f9f9f9;
            border: 1px solid #ddd;
            border-radius: 4px;
            overflow-y: scroll;
        }

        .notification-header {
            background-color: #fff;
            border-bottom: 1px solid #ddd;
            font-size: 18px;
            font-weight: bold;
            color: #333;
            padding: 10px;
        }

        .notification-list {
            max-height: 350px;
            background-color: #fff;
            padding: 10px;
        }

        .notification-item {
            display: flex;
            align-items: center;
            padding: 10px;
            border-bottom: 1px solid #ddd;
            cursor: pointer;
            transition: background-color 0.2s ease;
            white-space: inherit;
            text-decoration: none;
        }
        .notification-item a {
            text-decoration: none;
        }
        .notification-item-content {
            flex: 1;
        }
        .notification-item-text {
            font-size: 14px;
            color: #555;
        }

        .table-sortable th {
            cursor: pointer;
        }
        
        .table-sortable .th-sort-asc::after {
            content: "\25b4";
        }
        
        .table-sortable .th-sort-desc::after {
            content: "\25be";
        }
        
        .table-sortable .th-sort-asc::after,
        .table-sortable .th-sort-desc::after {
            margin-left: 5px;
        }
        
        .table-sortable .th-sort-asc,
        .table-sortable .th-sort-desc {
            background: rgba(0, 0, 0, 0.1);
        }

    </style>
</head>

{% endblock content %}

templates/globals/partials/_navbar.html
{% block content %}

<nav class="navbar navbar-expand-lg bg-body-tertiary">

    <div class="container-fluid">
        <a class="navbar-brand " href="{% url 'orion:lista_home' %}">Home</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false" name="chamado-menu">Chamado</a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'orion:novo_chamado' %}">Novo Chamado</a></li>
                        <li><a class="dropdown-item" href="{% url 'orion:lista_chamados' %}">Chamados Abertos</a></li>
                        <li><a class="dropdown-item" href="{% url 'orion:chamados_fechados' %}">Chamados Fechados</a></li>
                    </ul>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false" name="cadastros-menu">
                        cadastros
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'orion:empresas' %}">Empresas</a></li>
                        <li><a class="dropdown-item" href="{% url 'orion:equipamentos' %} ">Equipamentos</a></li>
                        <li><a class="dropdown-item" href="{% url 'usuarios:lista_usuarios' %} ">Usuários</a></li>
                    </ul>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Relatórios
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Horas Trabalhadas</a></li>
                        <li><a class="dropdown-item" href="#">Reembolso de Gastos de Viagem</a></li>
                        <li><a class="dropdown-item" href="#">Chamados</a></li>
                        <li><a class="dropdown-item" href="{% url 'orion:relatorio_ponto' %}">Ponto</a></li>
                    </ul>
                </li>

            </ul>

            <form class="d-flex me-2 mt-2" role="search" action="{% url 'orion:busca_chamados'%}">
                <input class="form-control me-2" type="search" placeholder="Pesquisar" aria-label="Pesquisar" name = 'q' value="{{termo_pesquisado}}" required>
                <button class="btn btn-outline-success" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
            </form>

            <ul class="nav navbar-nav navbar-right">   
                
                <!-- notificações -->
                <li class="nav-item dropstart mt-2 me-2">
                    <button id="notificacao-btn" class="notification btn btn-outline-primary" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fa-regular fa-bell"></i>
                        
                        <span id='numero-notificacoes' class="badge"></span>
                       
                    </button>
                    <ul class="dropdown-menu notification-container">
                        <div class="notification-header">Notificações</div>
                        <div id='notificacoes' class="notification-list">
                            <!--
                             notificações inseridas com js -->
  
                        </div>
                    </ul>
                
                    
                </li>
            
                <li class="nav-item dropdown mt-2">
                    
                    {% if user.is_authenticated %}
                    <button class="btn btn-outline-primary dropdown-toggle " type="button" data-bs-toggle="dropdown" aria-expanded="false">
                        {{ user.get_username |title }}
                        <!-- 
                        -->
                    </button>

                    {% else %}
                    <button class="btn btn-outline-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Usuáro
                    </button>
                    {% endif %}

                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'usuarios:dados_usuario' %}">Meus Dados</a></li>
                        <li><a class="dropdown-item" href="{% url 'usuarios:logout' %}" class="navText">Sair</a> </li>
                    </ul>
                </li>
                
        
            </ul>
        </div>
    </div>
</nav>
<script>

    $(document).ready(function(){
        
        $.ajax({
            type: "POST",
            url: "{% url 'orion:marcar_notificacao_como_lida' %}",
            data: {'id-notificacao': '1',  csrfmiddlewaretoken: '{{ csrf_token }}'},
            success: function(data) {
              // ação a ser executada se a requisição for bem sucedida
                
                //console.log(data)
                const noti =  JSON.parse(data['notificacoes']);
                        
                let notificacoesDiv = document.getElementById("notificacoes");
                
                noti.forEach((item) => {
                    //console.log(item.fields.verb, item.pk, item.fields.target_object_id); // Imprime o valor da chave "model" de cada objeto do arquivo JSON

                    // criando o formulário
                    let form = document.createElement("form");
                    form.classList.add("notificacao-form");
                    form.method = "post";
                
                    // adicionando o csrf_token
                    let csrf_token = document.createElement("input");
                    csrf_token.type = "hidden";
                    csrf_token.name = "csrfmiddlewaretoken";
                    csrf_token.value = "{{ csrf_token }}"; 
                    form.appendChild(csrf_token);
                
                    // criando o item de notificação
                    let notificationItem = document.createElement("div");
                    notificationItem.classList.add("notification-item");
                
                    let notificationItemContent = document.createElement("div");
                    notificationItemContent.classList.add("notification-item-content");
                    
                    let link = document.createElement("a");
                    link.href = "{% url 'orion:editar_chamado' 0 %}";
                    link.href = link.href.split('/').slice(0,-2).join('/')+'/'+item.fields.target_object_id+'/'

                    let notificationItemText = document.createElement("div");
                    notificationItemText.classList.add("notification-item-text");
                    notificationItemText.innerText = item.fields.verb; 
                    link.appendChild(notificationItemText);
                    notificationItemContent.appendChild(link);
                
                    let idNotificacao = document.createElement("input");
                    idNotificacao.setAttribute('value', item.pk )
                    idNotificacao.classList.add("hidden");
                    idNotificacao.type = "text";
                    idNotificacao.name = "id-notificacao";
                    notificationItemContent.appendChild(idNotificacao);
                
                    let markAsReadButton = document.createElement("button");
                    markAsReadButton.classList.add("mark_as_read");
                    markAsReadButton.type = "submit";
                    markAsReadButton.innerText = "Marcar como Lida";
                    notificationItemContent.appendChild(markAsReadButton);
                
                    notificationItem.appendChild(notificationItemContent);
                    form.appendChild(notificationItem);
                
                    notificacoesDiv.appendChild(form);
                }); 


                const count = document.querySelector('#numero-notificacoes');
                count.innerText = data.count
                if (data.count == 0){
                    count.setAttribute('class', 'hidden')
                    const notificationList  = document.querySelector('#notificacoes');
                    notificationList.innerText = "Sem notificações"
                }

                
                
                //console.log(notificacoesDiv)

            },
            error: function() {
              // ação a ser executada se a requisição falhar
            }
          });

        

    });

    
    // marca as notificacoes como lida
    document.addEventListener('submit', async (event) => {
        
        if (event.target.classList.contains('notificacao-form')) {
            event.preventDefault(); 
            form = event.target;

            const formData = new FormData(form);
            const response = await fetch("{% url 'orion:marcar_notificacao_como_lida' %}" , {
                method: 'POST',
                body: formData
            })
            .then(response => response.json())
            .then(data => {
                form.remove()
                const count = document.querySelector('#numero-notificacoes');
                count.innerText = data.count
                if (data.count ==0){
                    count.setAttribute('class', 'hidden')
                    const notificationList  = document.querySelector('#notificacoes');
                    notificationList.innerText = "Sem notificações"
                }
            });
            


        }
    });
    
</script>
{% endblock content %}